### ISSUE TITLE
unable to start taffybar

### ISSUE THREAD

**Issue by ghost** [travitch/taffybar#100]
Hi everyone,
I installed taffybar from haskell-core in archlinux and used the default template for taffybar.hs from the repository (https://github.com/travitch/taffybar/blob/master/src/System/Taffybar.hs) 
I keep getting the following error:
Configuration '/home/abhinav/.config/taffybar/taffybar.hs' changed. Recompiling.
Error occurred while loading configuration file.
Error: 
/home/abhinav/.config/taffybar/taffybar.hs:140:8:
    Could not find module ‘Paths_taffybar’
    Use -v to see a list of the files searched for.

/home/abhinav/.config/taffybar/taffybar.hs:141:8:
    Could not find module ‘System.Taffybar.StrutProperties’
    Use -v to see a list of the files searched for.
output of ghc-pkg list : http://pastebin.com/weR7NFg6 
and this is output of ghc-pkg check http://pastebin.com/54CQVMdZ

**Comment by saksham0808** [comment]
Perhaps going to .config/taffybar and then manually compiling it with
```ghc make taffybar.hs; ./taffybar``` might help. It works for me, my config is split into modules so I sometimes have to do this.
