### ISSUE TITLE
Make it easy to specify that you would like to monitor all network interfaces

### ISSUE THREAD

**Issue by eduarrrd** [travitch/taffybar#101]
With http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
interfaces can be called enpXsY instead of ethX. This breaks the last bit of "portability" like "luckily all my machines have eth0 and that's all I use so using the exact same taffybar.hs works and is trivial to keep in sync".

I suggest to a convenient to address "all interfaces" (with option to exclude some like "lo" or other edge cases).

Use case: "For each of my interfaces, show me <representation method e.g. graph> according to this <spec>."

**Comment by IvanMalison** [comment]
It's already possible to do something like this:

see https://github.com/IvanMalison/dotfiles/blob/0cb63f42936f72303a1a892d7b4d98ed8829f119/dotfiles/config/taffybar/taffybar.hs#L136

but we should make it so that this does not require custom code.
