### ISSUE TITLE
Just want advice on programming a widget for this

### ISSUE THREAD

**Issue by djvs** [travitch/taffybar#108]
I've been fiddling with taffybar here for a while, wrote a super small disk usage widget.  I have experience coding Qt in Ruby, but don't know GTK (besides the idea of 'widget' and some Pango), and am only C+-grade in Haskell so to speak.  I am wondering if you could share a few words on how I would go about writing a foobar-style/Start Menu-style widget.  

From what I understand my best starting point would probably be the window chooser component of the XMonadLog code?  I think a couple tips on producing a IO Widget or IO Gtk.Widget would go a long way toward spurring users to make some more, maybe.

Wondering also if there's a clean way to introduce a new string for formatting in the weather widget.  As you may know, some people use a weather font in Conky to produce graphical icons for it, but I hit a huge roadblock trying to replicate the code (I think my issue was with replicating defaultWeatherFormatter).

**Comment by travitch** [comment]
As you say, the best place to start looking would be the window chooser.  That uses a Menu widget and really uses it as just a menu.  You could *probably* do that, though you might not be able to embed all widget types within the menu.  If that ends up being problematic for you, I would just use a button press handler to show a VBox widget - you can pack arbitrary widgets into that.  Then you can set up a handler to hide the vbox however you like.  If you want even more control than a VBox provides, you could combine VBoxes and HBoxes (or a grid layout widget) for more complex things.

As for the weather formatting string - the weather "widget" is really just a gtk label, so you can use any [pango markup](http://www.gtk.org/api/2.6/pango/PangoMarkupFormat.html).  That would probably let you use the `font_family` attribute to set a specific font over a span of text.  That might be enough to handle inserting a few glyphs from an icon font.

**Comment by djvs** [comment]
Well, what I was referencing was that there seems to be some problem with the design pattern (or docs?) regarding the weatherConfig.  For example, if I try to replace this:

     wea = weatherNew (defaultWeatherConfig "KNYC") 10

with this:

      wea = weatherNew (WeatherConfig { weatherStation = "KNYC"
                                      , weatherTemplate = "$tempF$ °F"
                                      }) 10

Omitting the "weatherFormatter" argument, I get:

    Error:
    /home/me/taffybar.hs:95:25: Warning:
        Fields of `WeatherConfig' not initialised: weatherFormatter
        In the first argument of `weatherNew', namely
      `    (WeatherConfig
              {weatherStation = "KNYC", weatherTemplate = "$tempF$ \176F"})'
        In the expression:
          weatherNew
            (WeatherConfig
               {weatherStation = "KNYC", weatherTemplate = "$tempF$ \176F"})
            10
        In an equation for `wea':
            wea
              = weatherNew
                  (WeatherConfig
                     {weatherStation = "KNYC", weatherTemplate = "$tempF$ \176F"})
                  10

**Comment by travitch** [comment]
You probably want something like
```{.haskell}
let wcfg = defaultWeatherConfig "KNYC" { weatherTemplate = "<your format string>" }
     wea = weatherNew wcfg 10
```

That way you get the default formatter and just modify the template part.

**Comment by djvs** [comment]
Couldn't match expected type `WeatherConfig'
                with actual type `[Char]'
    In the expression: "KNYC"
    In the first argument of `defaultWeatherConfig', namely
      `"KNYC" {weatherTemplate = "hello"}'
    In the expression:
      defaultWeatherConfig ("KNYC" {weatherTemplate = "hello"})

**Comment by travitch** [comment]
oops, `(defaultWeatherConfig "KNYC") { ... }`

**Comment by djvs** [comment]
Got it, thanks
