### ISSUE TITLE
Fails on GHC 7.10

### ISSUE THREAD

**Issue by cstrahan** [travitch/taffybar#114]
This is with GHC 7.10 and taffybar 0.4.4 (**note:** I removed the bounds in the cabal file):

    [20 of 39] Compiling System.Taffybar.MPRIS2 ( src/System/Taffybar/MPRIS2.hs, dist/build/System/Taffybar/MPRIS2.o )
    
    src/System/Taffybar/MPRIS2.hs:78:28:
        No instance for (PrintfArg t0) arising from a use of ‘printf’
        The type variable ‘t0’ is ambiguous
        Note: there are several potential instances:
          instance [safe] PrintfArg GHC.Int.Int16 -- Defined in ‘Text.Printf’
          instance [safe] PrintfArg GHC.Int.Int32 -- Defined in ‘Text.Printf’
          instance [safe] PrintfArg GHC.Int.Int64 -- Defined in ‘Text.Printf’
          ...plus 13 others
        In the second argument of ‘($)’, namely
          ‘printf "%s - %s" (cutoff 15 artist) (cutoff 30 title)’
        In the expression:
          escapeMarkup
          $ printf "%s - %s" (cutoff 15 artist) (cutoff 30 title)
        In an equation for ‘msg’:
            msg
              = escapeMarkup
                $ printf "%s - %s" (cutoff 15 artist) (cutoff 30 title)
    
    src/System/Taffybar/MPRIS2.hs:83:9:
        Non type-variable argument
          in the constraint: Data.String.IsString [a]
        (Use FlexibleContexts to permit this)
        When checking that ‘cutoff’ has the inferred type
          cutoff :: forall a. Data.String.IsString [a] => Int -> [a] -> [a]
        In an equation for ‘setSongInfo’:
            setSongInfo w artist title
              = do { let msg :: String
                         ....;
                     postGUIAsync
                     $ do { labelSetMarkup w txt;
                            .... } }
              where
                  cutoff n xs
                    | length xs <= n = xs
                    | otherwise = take n xs ++ "\8230"

**Comment by cstrahan** [comment]
This patch resolves the issue above:

```patch
diff --git a/src/System/Taffybar/MPRIS2.hs b/src/System/Taffybar/MPRIS2.hs
index b347eba..43402d6 100644
--- a/src/System/Taffybar/MPRIS2.hs
+++ b/src/System/Taffybar/MPRIS2.hs
@@ -81,7 +81,7 @@ setSongInfo w artist title = do
     labelSetMarkup w txt
     widgetShowAll w
   where cutoff n xs | length xs <= n = xs
-                    | otherwise      = take n xs ++ "…"
+                    | otherwise      = take n xs ++ ("…" :: String)

 updatePlaybackStatus :: Label -> [(Variant, Variant)] -> IO ()
 updatePlaybackStatus w items = do
```

But that then leads to this error:

    [34 of 39] Compiling System.Taffybar.SimpleClock ( src/System/Taffybar/SimpleClock.hs, dist/build/System/Taffybar/SimpleClock.o )
    
    src/System/Taffybar/SimpleClock.hs:56:23:
        Ambiguous occurrence ‘TimeLocale’
        It could refer to either ‘Data.Time.Format.TimeLocale’,
                                 imported from ‘Data.Time.Format’ at src/System/Taffybar/SimpleClock.hs:16:1-23
                                 (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                              or ‘System.Locale.TimeLocale’,
                                 imported from ‘System.Locale’ at src/System/Taffybar/SimpleClock.hs:19:1-20
    
    src/System/Taffybar/SimpleClock.hs:63:59:
        Ambiguous occurrence ‘TimeLocale’
        It could refer to either ‘Data.Time.Format.TimeLocale’,
                                 imported from ‘Data.Time.Format’ at src/System/Taffybar/SimpleClock.hs:16:1-23
                                 (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                              or ‘System.Locale.TimeLocale’,
                                 imported from ‘System.Locale’ at src/System/Taffybar/SimpleClock.hs:19:1-20
    
    src/System/Taffybar/SimpleClock.hs:72:44:
        Ambiguous occurrence ‘TimeLocale’
        It could refer to either ‘Data.Time.Format.TimeLocale’,
                                 imported from ‘Data.Time.Format’ at src/System/Taffybar/SimpleClock.hs:16:1-23
                                 (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                              or ‘System.Locale.TimeLocale’,
                                 imported from ‘System.Locale’ at src/System/Taffybar/SimpleClock.hs:19:1-20
    
    src/System/Taffybar/SimpleClock.hs:97:49:
        Ambiguous occurrence ‘defaultTimeLocale’
        It could refer to either ‘Data.Time.Format.defaultTimeLocale’,
                                 imported from ‘Data.Time.Format’ at src/System/Taffybar/SimpleClock.hs:16:1-23
                                 (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                              or ‘System.Locale.defaultTimeLocale’,
                                 imported from ‘System.Locale’ at src/System/Taffybar/SimpleClock.hs:19:1-20
    builder for ‘/nix/store/k4p42q5jlxgnfi5jk1s1ikihkl5adds7-haskell-taffybar-0.4.4.drv’ failed with exit code 1
    error: build of ‘/nix/store/k4p42q5jlxgnfi5jk1s1ikihkl5adds7-haskell-taffybar-0.4.4.drv’ failed

**Comment by cstrahan** [comment]
With this final patch, taffybar builds on both ghc 7.8 and 7.10:

```patch
diff --git a/src/System/Taffybar/MPRIS2.hs b/src/System/Taffybar/MPRIS2.hs
index b347eba..43402d6 100644
--- a/src/System/Taffybar/MPRIS2.hs
+++ b/src/System/Taffybar/MPRIS2.hs
@@ -81,7 +81,7 @@ setSongInfo w artist title = do
     labelSetMarkup w txt
     widgetShowAll w
   where cutoff n xs | length xs <= n = xs
-                    | otherwise      = take n xs ++ "…"
+                    | otherwise      = take n xs ++ ("…" :: String)
 
 updatePlaybackStatus :: Label -> [(Variant, Variant)] -> IO ()
 updatePlaybackStatus w items = do
diff --git a/src/System/Taffybar/SimpleClock.hs b/src/System/Taffybar/SimpleClock.hs
index 8111313..0f93bd4 100644
--- a/src/System/Taffybar/SimpleClock.hs
+++ b/src/System/Taffybar/SimpleClock.hs
@@ -16,7 +16,9 @@ import qualified Data.Time.Clock as Clock
 import Data.Time.Format
 import Data.Time.LocalTime
 import Graphics.UI.Gtk
+#if !MIN_VERSION_time(1,5,0)
 import System.Locale
+#endif
 
 import System.Taffybar.Widgets.PollingLabel
 import System.Taffybar.Widgets.Util
```

**Comment by cstrahan** [comment]
I just opened PR #115 to resolve this.

**Comment by travitch** [comment]
Thanks for the report - I should have tested earlier.  I took a slightly different approach with my patch.  I'll cut a release shortly

**Comment by cstrahan** [comment]
Thanks!
