### ISSUE TITLE
windowSwitcher

### ISSUE THREAD

**Issue by f1u77y** [travitch/taffybar#118]
couldn't you add a widget that just shows active window and is not a `windowSwitcher` or fix such behaviour of `windowSwitcher`? (not enough height for symbols and those line above and below active window title) 
![1431954736](https://cloud.githubusercontent.com/assets/11313125/7681420/de556e06-fd78-11e4-8125-05d75da15f55.png)

**Comment by IvanMalison** [comment]
This is fixed with recent changes to windowSwitcher
