### ISSUE TITLE
FreedesktopNotifications module can produce invalid GTK markup

### ISSUE THREAD

**Issue by pjones** [travitch/taffybar#120]
The `notificationMaxLength` field is used to truncate output from the `notificationFormatter` function.  However, that function might return markup, and truncating it will produce invalid markup.  It seems like GTK should truncate the text directly instead of blindly doing it in TaffyBar.

I discovered this by accident when my `<span...` was getting cut off and therefore the GTK widget wasn't displaying any text at all.

**Comment by travitch** [comment]
Thanks for the report.  Should be fixed in 4a5cf4ba402833c9e8a853f61632b3741fdae342
