### ISSUE TITLE
Porting to Gtk3

### ISSUE THREAD

**Issue by RubenAstudillo** [travitch/taffybar#121]
There is a package from the gtk2hs project for gtk3. Is there intention of porting or are technical reason for not doing it?

**Comment by travitch** [comment]
I am interested in porting.  I haven't looked in to what would be required yet, but I can't imagine any technical reasons not to.  The biggest pain would probably be with gtk-traymanager, though I suspect that wouldn't be too difficult.

**Comment by qrilka** [comment]
Any news on this one? gentoo-haskell has dev-haskell/gtk masked in favor of dev-haskell/gtk3

**Comment by travitch** [comment]
It hasn't been a high priority for me, so I haven't looked in to it yet.
