### ISSUE TITLE
Problems with HStringTemplate dependency

### ISSUE THREAD

**Issue by djvs** [travitch/taffybar#127]
Apparently taffybar depends on an ancient version of HStringTemplate, so when you try to do cabal install taffybar, you get this:

```
Configuring HStringTemplate-0.3.1...
Building HStringTemplate-0.3.1...
Preprocessing library HStringTemplate-0.3.1...

Text/StringTemplate/GenericStandard.hs:12:8:
    Could not find module `Data.Generics.Aliases'
    Use -v to see a list of the files searched for.
Failed to install HStringTemplate-0.3.1
cabal: Error: some packages failed to install:
HStringTemplate-0.3.1 failed during the building phase. The exception was:
ExitFailure 1
taffybar-0.4.5 depends on HStringTemplate-0.3.1 which failed to install.
```

Can you update it maybe?  Honestly I'm not really positive what the problem is here.

**Comment by djvs** [comment]
Ran into the problem by making a fresh build of everything on Ubuntu 14.04 (cabal-install and ghc via both the official repos and ppa:hvr/ghc) with all required C/C++ libs.  Remedied it for the time being by copying .ghc and .cabal from another computer...

**Comment by djvs** [comment]
I emailed the author of HStringTemplate and he said to update the dependency to a newer version of HStringTemplate.

**Comment by travitch** [comment]
Thanks for the report.  The version of taffybar on hackage does not have any particular dependency bound on hstringtemplate.  In git there is a bound on recent versions, so I'll try to make a release today.

In the mean time, you could at least make it work by installing with

```.bash
cabal install taffybar --constraint='HStringTemplate >= 0.8'
```

**Comment by djvs** [comment]
Got further this time, but still stuck here:

     $ cabal-1.18 install taffybar --constraint='HStringTemplate >= 0.8'
     Resolving dependencies...
     In order, the following will be installed:
     pango-0.13.1.0 (reinstall) changes: directory-1.2.0.1 -> 1.2.4.0,
     process-1.1.0.2 -> 1.3.0.0
     gtk-0.13.9 (reinstall)
     gtk-traymanager-0.1.5 (reinstall)
     taffybar-0.4.5 (new package)
     Warning: Note that reinstalls are always dangerous. Continuing 
anyway...
     Configuring pango-0.13.1.0...
     Failed to install pango-0.13.1.0
     Last 10 lines of the build log ( 
/home/d/.cabal/logs/pango-0.13.1.0.log ):
     cabal-1.18: Error: some packages failed to install:
     gtk-0.13.9 depends on pango-0.13.1.0 which failed to install.
     gtk-traymanager-0.1.5 depends on pango-0.13.1.0 which failed to 
install.
     pango-0.13.1.0 failed during the configure step. The exception was:
     user error (
/tmp/pango-0.13.1.0-31945/pango-0.13.1.0/SetupWrapper.hs:60:49:
     Ambiguous occurrence `exeExtension'
     It could refer to either `Distribution.Simple.BuildPaths.exeExtension',
     imported from `Distribution.Simple.BuildPaths' at
/tmp/pango-0.13.1.0-31945/pango-0.13.1.0/SetupWrapper.hs:11:40-51
     or `System.Directory.exeExtension',
     imported from `System.Directory' at
/tmp/pango-0.13.1.0-31945/pango-0.13.1.0/SetupWrapper.hs:23:1-23
     (and originally defined in
`directory-1.2.4.0:System.Directory.Internal.Config')
     )
     taffybar-0.4.5 depends on pango-0.13.1.0 which failed to install.
