### ISSUE TITLE
Fullscreen does not cover taffybar

### ISSUE THREAD

**Issue by sakshamsharma** [travitch/taffybar#130]
This is a regular issue I experience . Opening a video on youtube in fullscreen for example pushes the video down by an amount equal to the height of taffybar. Somehow, moving the whole fullscreen video to another workspace makes it realize that the screen isn't that large as it appears. But that's just a hack to be able to view my subtitles properly.
That's certainly very annoying. Either taffybar should be hidden, or taffybar/xmonad should notify the window going fullscreen.
Not very sure how to fix this, any pointers (or better, a fix) would be welcome.

Just in case it's me messing up, here's my xmonad.hs
I don't call taffybar via my xmonad.hs except for pagerHints

```
main = do
  xmonad $ ewmh $ pagerHints $ defaultConfig {
    manageHook = manageDocks <+> manageHook defaultConfig <+> composeAll myManagementHooks
  , layoutHook = avoidStruts $ smartBorders $ myLayout
  , keys               = myKeys
  , workspaces         = myWorkspaces
  , startupHook        = myStartup
  , normalBorderColor  = myNormalBorderColor
  , focusedBorderColor = myFocusedBorderColor
  , modMask = mod4Mask
  , terminal = "urxvt"
  }
```

**Comment by travitch** [comment]
Are you using chrome or firefox?  I can't seem to reproduce that behavior with either.

The only difference I see between our layouts is that I have avoidStruts after smartBorders.

**Comment by saksham0808** [comment]
I'm using chrome here. Are there any events I can log, or some other data I can collect and put here? It's been really annoying for me this way.

**Comment by travitch** [comment]
Just one data point - full screen youtube videos in chrome cover taffybar for me.  The full screen that chrome uses seems to ignore struts (as it should)

**Comment by travitch** [comment]
Also, as far as I can tell, there wouldn't be any events to log on the taffybar side - maybe there are some xmonad hooks, but I don't know what they are.

**Comment by saksham0808** [comment]
Well that's weird. I don't see why it doesn't happen with me. As a last resort, let me know if something's missing here (though it is highly improbable):
```
main = do
  let memCfg = defaultGraphConfig { graphDataColors = [(1, 0, 0, 1)]
                                  , graphLabel = Just "mem"
                                  }
      cpuCfg = defaultGraphConfig { graphDataColors = [ (0, 1, 0, 1)
                                                      , (1, 0, 1, 0.5)
                                                      ]
                                  , graphLabel = Just "cpu"
                                  }
  let clock = textClockNew Nothing "<span fgcolor='orange'>%a %b %_d %H:%M:%S</span>" 1
      pager = myPager
      note = notifyAreaNew defaultNotificationConfig
      wea = weatherNew (defaultWeatherConfig "VILK") {weatherTemplate = "$tempC$°C @ $humidity$ hum"} 10
      mpris = mprisNew defaultMPRISConfig
      mem = pollingGraphNew memCfg 1 memCallback
      cpu = pollingGraphNew cpuCfg 0.5 cpuCallback
      wnet = netMonitorNewWith 10 "wlp8s0" 1 myNetFormat
      enet = netMonitorNewWith 10 "enp9s0" 1 myNetFormat
      batt  = batteryBarNew defaultBatteryConfig 30
      tray = systrayNew
  defaultTaffybar defaultTaffybarConfig { startWidgets = [ pager, note ]
                                        , endWidgets = [ tray, wea, clock, mem, cpu, batt, enet, wnet, mpris ]
                                        }
```

**Comment by travitch** [comment]
Have you tried this? 

http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-ManageHelpers.html

In particular, the `isFullscreen -?> doFullFloat` in manageHook.  I realized I do that, and I think that is responsible for making fullscreen video work in general.

**Comment by travitch** [comment]
Did `doFullFloat` help at all?

**Comment by saksham0808** [comment]
I haven't been able to write it in my xmonad.hs yet, didn't get much time recently.
```
    manageHook = manageDocks <+> manageHook defaultConfig <+> composeAll myManagementHooks
```
Where myManagementHooks is currently empty. I'm not too great at haskell yet, I'd love if you could write the exact syntax.

**Comment by saksham0808** [comment]
Interestingly, `doFullFloat` helped, videos played full screen and Taffybar got hid. But I cannot say the same about Youtube videos for example (any video played via Chrome). Via firefox.. well it's not going full screen as of yet, stops working when I try it, looking into that.
Anyhow, does anyone else have this issue with Chrome?

**Comment by ThinkRedstone** [comment]
I still have this issue, if someone knows of a workaround or fix

**Comment by ThinkRedstone** [comment]
going full screen in chrome still has the taffybar above the window, so this problem persists for me

**Comment by IvanMalison** [comment]
@sakshamsharma @ThinkRedstone 
I'd like some clarity about the problem that this issue is describing.

It seems to me that the original issue was that going full screen wouldn't use all of the screen because doFullFloat was not in @sakshamsharma xmonad config.

Now it seems that you are describing a different issue, which I have also seen, which is that in certain cases, taffybar will appear ON TOP of a window that has gone full screen. This is a fundamentally different problem though, and as such it should be tracked by a different issue (#275).

> ia firefox.. well it's not going full screen as of yet, stops working when I try it, looking into that.

This is just an issue with the way that firefox goes fullscreen, and not really with taffybar. Nothing we can do about that.
