### ISSUE TITLE
Running taffybar with two monitors

### ISSUE THREAD

**Issue by willprice** [travitch/taffybar#133]
Hi,

When I run taffybar with the example configuration (or default config) I get the following message when launching from a terminal:

```
Monitor 0 is not available in the selected screen
```

A white bar is displayed at the top of the display on DP2, instead of the expected black taffybar.

```
$ xrandr
Screen 0: minimum 8 x 8, current 3760 x 1920, maximum 32767 x 32767
LVDS1 connected (normal left inverted right x axis y axis)
   1366x768      60.02 +
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   680x384       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   1920x1080     60.00    60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.08    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 connected 1200x1920+2560+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       60.00  
   720x400       70.08  
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

Any idea on what the issue might be and how to resolve it?

Many thanks,

**Comment by travitch** [comment]
When you say white bar, do you mean an empty white bar, or a white bar with widgets?

A recent commit (be60703daf6a60ffdd417a6733fcf90772af826d) fixed the issue with the desktop number error.  If the bar has widgets and is just the wrong color, another commit (45ff40992c8fe5593d5f3e03ef0765168c6325fb) probably took care of that.

**Comment by willprice** [comment]
Hi,

I've just tried building from master, this has fixed the issue of a white bar with no widgets appearing and I now get my expected bar, however I still get the error message on the command line, what exactly is it referring to? 

Do *monitor*s refer to actual physical monitors and *screen*s xrandr's concept of a screen which can be made up of multiple monitors?

**Comment by travitch** [comment]
I had to go back and check.  The monitor number refers to a physical monitor in an X screen (on the default display), at least as interpreted by gdk/gtk

**Comment by saksham0808** [comment]
How I use taffybar with multiple monitors is as following:
So taffybar shows up on only one monitor at a time. On my PC this creates problems, swapping workspaces between monitors causes a good amount of flickering and shifting (~500ms or more) because of the different amount of vertical space available on the two monitors.
I proceeded to let one taffybar running, and then went to my config, changed the default monitor to 1, and then started another instance of taffybar. Stashed the changes on my config. This works for me, as I don't shutdown my PC often. 
There should be a better way to have taffybar on both the monitors.

**Comment by willprice** [comment]
@travitch, thanks for your help (apologies for the very delayed response), I'm now happily using taffybar!

@saksham0808, thanks for weighing in, it'd be nice if taffybar had better support, I'd try my hand at dipping in and helping, but my Haskell knowledge is probably insufficient :(

**Comment by jirkamarsik** [comment]
@sakshamsharma I know this discussion is quite old, but if someone in the future is wondering how to run taffybar on two monitors simultaneously, you can do this:

```
import Control.Concurrent
...
main = do
...
  forkIO $ defaultTaffybar $ myTaffybarConfig { monitorNumber = 0 }
  defaultTaffybar $ myTaffybarConfig { monitorNumber = 1 }
```
Don't forget that you can use all of Haskell to run/customize your taffybar. :-)

**Comment by IvanMalison** [comment]
@jirkamarsik taffybar has internal support for multiple monitors now, so that approach should no longer be necessary
