### ISSUE TITLE
Example configuration doesn't match screenshot

### ISSUE THREAD

**Issue by marbu** [travitch/taffybar#134]
When I install taffybar 0.4.5 and configure it based on example configuration
(`xmonad.hs.example`, `taffybar.hs.example` and `taffybar.rc` files), window
switcher shows all virtual desktops regardless of the fact that most of them
are empty. Based on screenshot from readme file and default behaviour of
xmobar, I would expect that only virtual desktops which contains at lest
one window are shown.

Could you reconfigure default examples to achieve this behaviour?
## Actual results

All desktops are visible in the switcher

```
[1] 2 3 4 5 6 7 8 9 : Full : ...
```
## Expected results

Only desktops which contains some window(s) are displayed:

```
[1] 2 : Full : ...
```

**Comment by marbu** [comment]
I'm sorry for abusing this issue tracker when asking for help with configuration, it's possible that I'm just doing something wrong. I hope you don't mind  and thank you for your help.

**Comment by saksham0808** [comment]
Happened with me too. I went and copied some of the code from the Workspace Switcher and put in inside my config.
Have a look at my config [here on github](https://github.com/saksham0808/my-configs/blob/master/.config/taffybar/taffybar.hs). Specifically, look at the myPager and myPagerConfig definitions. I had done some changes in the default pager config and added it in my config so that I don't have that problem.

**Comment by marbu** [comment]
@saksham0808 thanks a lot for the hint

Basically all I need to do is to redefine `emptyWorkspace` of `defaultPagerConfig` to  `\xs -> ""`. See my [this commit in my taffybar config](https://github.com/marbu/xmonad/commit/0407f99c4c168b9e55bed754ef403b726dca89ea).  So it's actually quite easy to reconfigure this, I should have checked sources of the pager configuration ...

That said, I still think it would make more sense to use this configuration by default.

**Comment by saksham0808** [comment]
Well yes that looks quite fine. I had made this change within one hour of starting with taffybar, and didn't even know much Haskell then :tongue: Anyway, :+1: for the commit.

**Comment by travitch** [comment]
The behavior of the example configuration changed at some point when the formatting code was reworked.  I also prefer that empty workspaces not be displayed, for what it is worth.  I would be fine with an updated example or a discussion about improved defaults.

**Comment by saksham0808** [comment]
#135
