### ISSUE TITLE
What's the point of "Tray icon removed" message?

### ISSUE THREAD

**Issue by qrilka** [travitch/taffybar#136]
When I run taffybar from the terminal I see a lot of those because of https://github.com/travitch/taffybar/blob/97b4d2f6feffcab8e5d73523d7b6148b64177e31/src/System/Taffybar/Systray.hs#L21
@travitch is there any motivation for that message to appear in console?

**Comment by travitch** [comment]
It was to help me get the system tray working

**Comment by qrilka** [comment]
Sorry, do you mean that without output to stdout system tray doesn't work?

**Comment by travitch** [comment]
No, I just mean that I never got around to removing the output.
