### ISSUE TITLE
Running multiple instances

### ISSUE THREAD

**Issue by Tordek** [travitch/taffybar#139]
I run a dual head setup, and Taffybar's widgets would be a great replacement for my setup. However, since Taffybar requires the config file to be in a particular location, it's not possible (except with some bash script, I suppose) to run two instances, each with a different config.

Either that, or a second options would be to be able to have more than one Taffybar window on the same config file.

The first option seems simpler, though.

**Comment by sakshamsharma** [comment]
I used to keep a sed script to launch 2 instances.
So it would first start one instance of taffybar. Then it would use the ```sed``` command to replace the monitor number in the config file. Relaunches taffybar. Then uses sed again to restore the file to its original state.
Hacky workaround, but works.

**Comment by alem0lars** [comment]
can you share the script ?

**Comment by IvanMalison** [comment]
@alem0lars See What I wrote in #61 for a better approach

**Comment by IvanMalison** [comment]
This should probably be closed now
