### ISSUE TITLE
Allow building with stack

### ISSUE THREAD

**Issue by sakshamsharma** [travitch/taffybar#140]
Cabal gives a lot of issues with almost everything I try to do on Gentoo. It'd be great if someone could write a stack build file.

**Comment by travitch** [comment]
This would depend on willdonnelly/dyre#29

**Comment by PkmX** [comment]
My current workaround is installing taffybar (and all libraries your `taffybar.hs` depends on) to stack's implicit global and then `stack exec taffybar`. It seems to work well for me so far; since I'm not launching anything from taffybar, the modified environment from stack doesn't bother me much (as opposed to XMonad).

**Comment by sakshamsharma** [comment]
Now that I knew a little more about stack, I've been trying to build taffybar with various lts build plans. Apparently none of them work out of the box (I tried quite a handful from 3.0 to 5.2).

**Comment by PkmX** [comment]
@sakshamsharma I'm currently building taffybar from lts-5.3 on Arch Linux and it works. You have to add `[gtk-traymanager-0.1.6, xmonad-contrib-0.12, X11-xft-0.3.1, alsa-core-0.5.0.1]` to `extra-deps` though because those packages are not in the snapshot.

**Comment by sakshamsharma** [comment]
@PkmX I tested out a bit. Seems to work nicely. Though some people might need an extra line in the stack.yaml for gtk-0.13.0 (Like I needed).
Should someone submit a PR for the stack.yaml file?

**Comment by travitch** [comment]
For the record, I would accept a patch like that.  I didn't realize that `stack exec` would work with taffybar and dyre.  If so, I wouldn't mind making that a supported configuration.

**Comment by sakshamsharma** [comment]
#144

**Comment by sakshamsharma** [comment]
Although this does work, I'm not entirely sure about how one would access the Taffybar libs from Xmonad using this. With cabal you could find the libs conveniently in a folder.
