### ISSUE TITLE
Comment in taffybar.rc

### ISSUE THREAD

**Issue by sid-kap** [travitch/taffybar#142]
Is there a way to make comments in taffybar.rc?

**Comment by kmicu** [comment]
You can use `#`, because `taffybar.rc` is a GTK2 resource file.

> An RC file is a text file which is composed of a sequence of declarations. '#' characters delimit comments and the portion of a line after a '#' is ignored when parsing an RC file.

 ― https://developer.gnome.org/gtk2/stable/gtk2-Resource-Files.html

**Comment by sid-kap** [comment]
Thanks!
