### ISSUE TITLE
New mails in maildir

### ISSUE THREAD

**Issue by rogorido** [travitch/taffybar#143]
Is it possible to add the possibility to check whether there are new emails in a maildir/mbox/etc.?

**Comment by travitch** [comment]
In principle it wouldn't be hard, but I'm not aware of any libraries handling watching a maildir.  Maybe it wouldn't be too hard to cook up using inotify or something, but I'm not familiar with the mechanics of maildirs.

**Comment by rogorido** [comment]
Yes, xmobar uses inotify. Thanks for your answer in any case!
