### ISSUE TITLE
One taffybar on each monitor?

### ISSUE THREAD

**Issue by abbradar** [travitch/taffybar#153]
Can taffybar be configured so that there is one instance spawned for each monitor? I imagine it would need some cooperation with xmonad or another supervisor which would ensure that instances are spawned and killed when monitors are dynamically added or removed. If I have skipped something obvious in the manual, sorry!

BTW, in TODO you write:

> Better behavior when adding/removing monitors (never tried it)

, but, apart from the above question, taffybar's support for adding/removing monitors seems nice to me. When I reconfigure xrandr, taffybar automatically moves to the new primary primary monitor and resizes itself so it will fit.

**Comment by sakshamsharma** [comment]
An easier implementation would be to allow a list for the `monitorNumber = 1` flag. If there's a list, then take it one by one, and spawn multiple instances, one for each monitor. I had a script do it for me at one time. Would be nice if the `taffybar` binary can do this.

**Comment by abbradar** [comment]
Hm, if I understand correctly it won't work with case when monitors are attached/detached _after_ taffybar is started, so you still need a supervisor process to monitor this. It may as well be integrated into taffybar itself, though.

**Comment by sakshamsharma** [comment]
Well, that's right. But this might be a smaller step in that direction. 
In any case, someone needs to start in some direction. I would have, but 
running quite busy these days.

**Comment by IvanMalison** [comment]
I'm going to take a swing at this.

For now it won't handle the case of added/removed monitors (but you'll always be able to restart taffybar to get the correct behavior).
