### ISSUE TITLE
Weather service discontinued

### ISSUE THREAD

**Issue by qrilka** [travitch/taffybar#169]
From http://weather.noaa.gov/pub/data/observations/metar/decoded/KMSN.TXT
I get
```
This Service is no longer available

In Accordance with NWS Service Change Notice 16-16 this service has been discontinued. Please see Weather.gov and tgftp.nws.noaa.gov (raw data)
```
but it looks like http://tgftp.nws.noaa.gov/data/observations/metar/decoded/KMSN.TXT shows correct data

**Comment by travitch** [comment]
Thanks - I sort of knew this was coming, but hadn't done anything yet.  I'll try to switch to this new base URL.

One day, I hope to switch to a more principled library

**Comment by travitch** [comment]
oh, actually it looks like this change is already made on master.  I should cut a new release.

**Comment by qrilka** [comment]
Oh, I have missed that...
New release would be great @travitch

**Comment by simlu** [comment]
Struggling with this right now... A release would be great. Don't feel like packing my own deb without having a version to reference.

**Comment by lukas-gitl** [comment]
Wrote my own minimalistic one here:
> **[Full Example](https://github.com/simlu/xmonad/blob/master/config/.config/taffybar/taffybar.hs)**

**Excerpt Below:**
```haskell
textWeatherNew :: String
               -> String
               -> Double
               -> IO Gtk.Widget
textWeatherNew fmt station period = do
  label <- pollingLabelNew fmt period (callback station)
  Gtk.widgetShowAll label
  return label
  where
    callback station = do
      body <- getUrl ("http://tgftp.nws.noaa.gov/data/observations/metar/decoded/" ++ station ++ ".TXT")
      name <- readProcess "grep" ["-o", "-P", "^.*(?=,.*\\(" ++ station ++ "\\))"] body

      tempLine <- readProcess "grep" ["-o", "-P", "(?<=Temperature:).*$"] body
      temp <- readProcess "grep" ["-o", "-P", "(?<=\\().*?(?= C\\))"] tempLine

      let template = ST.newSTMP fmt
      let template' = ST.setManyAttrib [ ("name", strip name), ("tempC", strip temp) ] template
return $ ST.render template'
```

**Comment by IvanMalison** [comment]
New release up on hackage!
