### ISSUE TITLE
serious performance regression for _NET_WM_DESKTOP

### ISSUE THREAD

**Issue by teleshoes** [travitch/taffybar#174]
noticed that switching workspaces was massively sluggish after i rebased on the latest.

i bisected the regression to `1a5c422`.

the workspace-switcher now takes about a full second to update. its so slow now that by the time it updates, im somewhere else.

if i switch back and forth between two workspaces about 20 times, the workspace-switcher freezes and my cpu spikes for ~70s.

perhaps this should be added as a configuration option to fix i3wm

@sakshamsharma @travitch

**Comment by teleshoes** [comment]
1) actually, the whole taffybar freezes
2) the regression only happens with `useImages=True`

**Comment by IvanMalison** [comment]
@teleshoes A _NET_WM_DESKTOP callback is still needed to appropriately set the icon if the icon that you are interested in is not on the current workspace, so it seems to me that it DOES make sense to listen on this callback. It seems likely that what is slow is the actual setting of images itself. It might make sense to start doing some caching for the icons (i.e. only set the pixelbuffer for the image if the associate icon IS actually changed)

**Comment by ewolk** [comment]
1) actually, _NET_WM_DESKTOP is not necessary for setting icons on non-active workspaces
2) yea, the setting of the icons is what takes cpu time, but this regression is because the _NET_WM_DESKTOP callback code is resulting in it being called many many times when the workspace changes
3) the solution is to separate out exactly what needs updating on what events. this isnt quite trivial to do. IMO, a good interim solution would be to add a config option to disable listening to _NET_WM_DESKTOP
4) yea, i experimented with caching pixbufs
  a) you cannot cache by window title and window class, as the icon for an app can change even while the program is still running, let alone run-to-run
  b) the performance was more or less identical
  c) the caching code was fairly complicated on my first pass, and might be a burder to maintain in future, i think.
  d) i truly dont think caching is an improvement, as **its quite fast as long as you dont call it 64 times when you switch workspaces**

**Comment by ewolk** [comment]
tested with unsafePerformIO in activecb with 10 windows in total, spread over 5 workspaces:
1) _NET_WM_DESKTOP is called 4-15 times when i switch windows within a workspace
2) _NET_WM_DESKTOP is called 8-25 times when i switch workspaces
3) _NET_WM_DESKTOP is called exactly 7 times when i push enter in urxvt

(all those things result in a single _NET_CURRENT_DESKTOP event)

=> whatever needs to happen on that event definitely needs to happen a lot less frequently than it is happening right now, in xmonad anyway
@sakshamsharma @travitch @IvanMalison

**Comment by teleshoes** [comment]
1) actually, _NET_WM_DESKTOP is not necessary for setting icons on non-active workspaces
2) yea, the setting of the icons is what takes cpu time, but this regression is because the _NET_WM_DESKTOP callback code is resulting in it being called many many times when the workspace changes
3) the solution is to separate out exactly what needs updating on what events. this isnt quite trivial to do. IMO, a good interim solution would be to add a config option to disable listening to _NET_WM_DESKTOP
4) yea, i experimented with caching pixbufs
  a) you cannot cache by window title and window class, as the icon for an app can change even while the program is still running, let alone run-to-run
  b) the performance was more or less identical
  c) the caching code was fairly complicated on my first pass, and might be a burder to maintain in future, i think.
  d) i truly dont think caching is an improvement, as **its quite fast as long as you dont call it 64 times when you switch workspaces**

EDIT: commented as the wrong user before, sorry

**Comment by teleshoes** [comment]
tested with unsafePerformIO in activecb with 10 windows in total, spread over 5 workspaces:
1) _NET_WM_DESKTOP is called 4-15 times when i switch windows within a workspace
2) _NET_WM_DESKTOP is called 8-25 times when i switch workspaces
3) _NET_WM_DESKTOP is called exactly 7 times when i push enter in urxvt

(all those things result in a single _NET_CURRENT_DESKTOP event)

=> whatever needs to happen on that event definitely needs to happen a lot less frequently than it is happening right now, in xmonad anyway
@sakshamsharma @travitch @IvanMalison

**Comment by travitch** [comment]
Maybe you could have the event handler for _NET_CURRENT_DESKTOP push some smallish piece of data onto some kind of queue and have an asynchronous thread pull the data off (and coalesce identical requests)?  Think of it like an interrupt in C.

**Comment by teleshoes** [comment]
well, to be clear, _NET_CURRENT_DESKTOP happens exactly once for all the events that it should happen for.

the trouble is that the new code for i3wm is now calling these methods dozens for times, because of the handler of _NET_WM_DESKTOP.

that being said, all we have to do is handle the icon stuff in NET_CURRENT and whatever it is that i3wm in NET_WM. since i have no idea what it is that i3wm needs, i would like @sakshamsharma to take a look.

no need to add the complexity of mvars and concurrency when it already only happens once.

@travitch

**Comment by teleshoes** [comment]
in the meantime, this is a pretty serious regression. taffybar is unusably slow with images right now.
(and images were quite fast before this change)

would you like me to make a PR to quickly fix this (do everything in _NET_CURRENT_DESKTOP, do everything except images in _NET_WM_DESKTOP)?

a better solution would be to split whats really needed between the two so that theres no unnecessary overlap, but like i say, i dont need _NET_WM_DESKTOP at all so i have no idea what it does that IS necessary.

**Comment by IvanMalison** [comment]
We might want to reopen this since my fix only applies to workspace HUD (not WSS)
