### ISSUE TITLE
New release on Hackage ? 

### ISSUE THREAD

**Issue by PierreR** [travitch/taffybar#179]
The current release on hackage is the current `0.4.6`.

Will you release a new version soon on hackage ?  I have been caught by the renaming in the Battery.hs file  while looking around at configuration on the web ;-)

Thanks.

**Comment by qrilka** [comment]
yeah, with new release e.g. #169 could be also closed
@travitch is there something stopping you to create a new release?

**Comment by travitch** [comment]
It is just a matter of time.  I'd like to at least write up a good changelog and migration guide.

I don't actually use taffybar myself these days, so I should really find a new maintainer.  I'll try to get to it this week.

**Comment by travitch** [comment]
I started a changelog (https://github.com/travitch/taffybar/blob/master/CHANGELOG.md) for a new release.  Can those who have added things recently take a look and see if I have missed any interesting commits?  Especially anything involving breaking API changes. Also, feel free to remind me of anything I've missed that should go into the release - I'm sure there are a bunch of things. @IvanMalison @escherdragon @teleshoes @sakshamsharma

**Comment by IvanMalison** [comment]
@travitch Multiple monitor support was also added in the workspaceHUD branch, along with a [config field](https://github.com/travitch/taffybar/blob/master/src/System/Taffybar.hs#L183) to control it.

I have a [branch](https://github.com/IvanMalison/taffybar/tree/toggleable) that allows taffybar to be toggled on each monitor [see usage here](https://github.com/IvanMalison/dotfiles/blob/master/dotfiles/config/taffybar/lib/ToggleMonitor.hs)

I will make a pull request to add this change to the changelog.

> I don't actually use taffybar myself these days, so I should really find a new maintainer. I'll try to get to it this week.

I would be happy to help out with this in any way you feel is appropriate. I feel pretty comitted to using taffybar for the foreseable future, and though I haven't read every last bit of taffybar's source, I'm pretty comfortable with its most important components.

**Comment by crocket** [comment]
@travitch If you didn't use taffybar, what would you use instead?

**Comment by travitch** [comment]
I use i3 these days, which comes with its own simple bar.

**Comment by sakshamsharma** [comment]
Interesting. I myself landed on i3 (because Xmonad has been misbehaving and crashing). I kept using Taffybar even on i3 (looks much better than i3bar), but it recently stopped working completely. I haven't managed to look into it due to paucity of time, but perhaps give it a shot if it works for you? It works perfectly fine on i3.

**Comment by crocket** [comment]
@travitch I also thought about trying i3. Although I can write haskell, xmonad API is simply too complex for most of my needs. The initial learning curve is very deep. Altough I'm getting the hang of it, I'm still drowning.

**Comment by IvanMalison** [comment]
> Interesting. I myself landed on i3 (because Xmonad has been misbehaving and crashing). I kept using Taffybar even on i3 (looks much better than i3bar), but it recently stopped working completely. I haven't managed to look into it due to paucity of time, but perhaps give it a shot if it works for you? It works perfectly fine on i3.

Are you building XMonad from source or using a version distributed with a package manager or cabal/stack?

XMonad has always been incredibly stable for me, I wonder what's making your setup crash.


> I use i3 these days, which comes with its own simple bar.

:( . I can't imagine going back to i3 after moving to XMonad. I guess different people like different things.

**Comment by nyarly** [comment]
I'd like to "me too" a new release - I'm installing Taffybar through Nix, and they're looking to Hackage as "stable releases." I'd love to have multi-monitor stuff.

**Comment by IvanMalison** [comment]
> I'd love to have multi-monitor stuff.

@nyarly  You'll probably want #186 to make it in before the release then. I changed some of the interfaces to it in that PR, and it also allows you to dynamically toggle which workspaces the bar is visible on.

@travitch I think it would be great if #189 also made it in.

I just remembered that @travitch asked us to help with the changelog stuff and that I never did that, so I'll work on that right now.

**Comment by IvanMalison** [comment]
I think that once we get the release ironed out we should also handle #141

**Comment by nyarly** [comment]
I'd be more than happy with monitorFilter for the time being; if there's a stable commit in master that includes that, I'd love to see a release ASAP with that, and toggle-per-monitor Real Soon.

**Comment by IvanMalison** [comment]
> I'd be more than happy with monitorFilter for the time being
The thing is that I think it's probably better not to cut a release with monitorFilter and then later remove monitorFilter once it is merged with #186.

**Comment by IvanMalison** [comment]
@travitch I've added entries to the changelog in #186 . Lets do a new release. Let me know if I can help in any way.

**Comment by PierreR** [comment]
Before releasing, I would like to mention an small annoyance that I have experienced with the latest git version (a few days ago). I have this taffybar.rc file:
``` 
style "taffybar-default" {
  color["black"] = "#000000"
  color["white"] = "#ffffff"
  color["green"] = "#bcdb95"
  color["red"]   = "#ff0000"
  color["burgundy"] = "#473343"

  bg[NORMAL]   = @burgundy
  fg[NORMAL]   = @white
  text[NORMAL] = @white
  fg[PRELIGHT] = @green
  bg[PRELIGHT] = @burgundy
}

style "taffybar-active-window" = "taffybar-default" {
  fg[NORMAL] = @green
}

style "taffybar-notification-button" = "taffybar-default" {
  text[NORMAL] = @red
  fg[NORMAL]   = @red
}

style "taffybar-workspace-border-active" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}
style "taffybar-workspace-border-visible" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}
style "taffybar-workspace-border-empty" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}
style "taffybar-workspace-border-hidden" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}
style "taffybar-workspace-border-urgent" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}
style "taffybar-workspace-label-border" = "taffybar-default" {
  bg[NORMAL] = @burgundy
}

widget "Taffybar*" style "taffybar-default"
widget "Taffybar*WindowSwitcher*label" style "taffybar-active-window"
widget "*NotificationCloseButton" style "taffybar-notification-button"
widget "*Workspace-*-active*" style "taffybar-workspace-border-active"
widget "*Workspace-*-visible*" style "taffybar-workspace-border-visible"
widget "*Workspace-*-empty*" style "taffybar-workspace-border-empty"
widget "*Workspace-*-hidden*" style "taffybar-workspace-border-hidden"
widget "*Workspace-*-urgent*" style "taffybar-workspace-border-urgent"
widget "*Workspace-label-*" style "taffybar-workspace-label-border"

gtk-font-name = "DejaVu Sans Mono Bold 10"
```
The color of the bar is `burgendy` but the title of the current running application have a black border that I don't know how to get rid off ... Sorry no screenshot for now as I have reverted to the latest release to avoid the problem ;-)

**Comment by IvanMalison** [comment]
Try adding
```widget "*WindowTitle*" style "taffybar-active-window"```

**Comment by shwsun** [comment]
I am using taffybar now and will probably stick with it for a while. I am happy to do some regular stuff (like review some PR, do some testing stuff, although I dont have much experience on haskell)

I am using XMonad on Ubuntu.

**Comment by IvanMalison** [comment]
@PierreR were you ever able to try my suggestion?

**Comment by PierreR** [comment]
Yes thanks I am pretty sure your suggestion works. Thanks. I am still using and love taffybar!

**Comment by nyarly** [comment]
Any progress on getting a release out?

**Comment by IvanMalison** [comment]
@nyarly Seems like the last @travitch said about this was that he had created a Changelog for a new release (https://github.com/travitch/taffybar/issues/179#issuecomment-289195053), and that people should add to it. I added entries to the changelog for most of the new features that I added, but I know that there a bunch of bug fixes that haven't been added. There are a lot of outstanding pull requests that could probably make it in before a release, but it also seems like getting something out would be better than waiting at this point.

**Comment by IvanMalison** [comment]
I've added changelog info about all my bugfixes in #227

**Comment by IvanMalison** [comment]
@nyarly btw I've added a quick_start script to setup a from source build using stack (which is probably the best way to use taffybar anyway), which will let you get all the most recent updates without an upgrade in hackage.

You can find it here https://github.com/travitch/taffybar/blob/master/quick-start.sh

Running it should set everything up for you. You may need to edit the cabal file if you use any additional dependencies in your config.

**Comment by PierreR** [comment]
@IvanMalison By the way there is a `hackage` policy that can be activated when a package is not maintained anymore. I believe they are calling the current maintainer, wait for a week or two and then transfer the ownership. That might simplify the decision process.  I am also using nix and would be generally to lazy to bother upgrading unless it is out in hackage. I am just saying this because on the long run, not having more users testing and using the latest version might be a problem.

**Comment by nyarly** [comment]
I'm in @PierreR's boat - on Nix, not really interested in using a different install process. Arguably we could add something like "taffybar-head" to nixpkgs, but not having actual releases is (at best) depressing. Maybe it makes more sense to switch to polybar and figure out resource graphs there?

**Comment by IvanMalison** [comment]
@PierreR @nyarly 
@travitch is still pretty actively maintaining taffybar, so I think that trying to do a hostile takeover of the hackage package is probably a bad idea.

> "taffybar-head" to nixpkgs,

That might be a good idea though. I think that a significant portion of taffybar users like to build from source anyway so that they can get the latest updates (I will probably always do this).

> not having more users testing and using the latest version might be a problem

@PierreR Yes, I agree I think this has become a problem. There are, at this point, a huge number of major major changes to taffybar that have not made it into a release:

## New Features

 * Support for multiple batteries via ``batteryContextsNew`` (Edd Steel)
 * Add support for IO actions to configure vertical bar widgets
 * Images in the workspace switcher - images are taken from EWMH via \_NET\_WM_ICON (Elliot Wolk)
 * Preliminary support for i3wm (Saksham Sharma)
 * A new workspace switcher widget called WorkspaceHUD (Ivan Malison)
 * Support for multiple network interfaces in NetMonitor (Robert Klotzner)
 * Support for taffybar on multiple monitors (Ivan Malison)
 * d-bus toggling of taffybar per monitor (Ivan Malison)
 * Add a pager config field that configures the construction of window switcher titles (Ivan Malison)
 * Quick start script for installing from git with stack (Ivan Malison)

## Bug Fixes

 * Fixes for outdated weather information sources
 * Various styling fixes in the gtkrc code
 * Share a single X11Connection between all components to fix the `user error (openDisplay)` error (Ivan Malison)
 * Call initThreads at startup. This fixes ```taffybar-linux-x86_64: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.```

**Comment by PierreR** [comment]
Just for information, I am shipping a box that uses `taffybar` to twenty users or so. This is probably not that much but might explain why I am not so keen on using a `head` version ;-)

**Comment by PierreR** [comment]
As another aside, I have came across [that page](https://dunst-project.org/static/image.png) recently and I immediately wonder how I could achieve such a slick design with the new version of taffybar ;-)

**Comment by IvanMalison** [comment]
@PierreR 
I've made my taffybar look pretty similar to that:

![taffybaroct2017](https://user-images.githubusercontent.com/1246619/31249745-59577a60-a9cd-11e7-9f08-4e3f756ed43d.png)

I'm pretty sure I could get taffybar to look pixel for pixel pretty similar to that.

**Comment by PierreR** [comment]
@travitch that's exiting. I would love to have the status bar divides into 3 sections (favorite programs displaying as icons, virtual desktop (the usual 1 [2] ...) and then the notification area (cpu, time, ...)

I will give it a go as soon as a release is happening. Thanks for your work on the project !

**Comment by IvanMalison** [comment]
> divides into 3 sections

Ahh, taffybar does not currently have the ability to do that. I don't think it would be too hard to add though.

**Comment by shwsun** [comment]
@IvanMalison I think it is really cool that we will soon have new releases.I am using xmonad (along with taffybar) as my daily workspace, and I would love to contribute in some ways (maybe some bug fixes, new release testing, ubuntu package maintaining, PR reviewing etc).

**Comment by nyarly** [comment]
@travitch @IvanMalison Ping re a release? The difference between master and v0.4.6 is kind of huge. https://github.com/travitch/taffybar/compare/v0.4.6...master

**Comment by IvanMalison** [comment]
@travitch I can't really speak to that branches stability since I haven't actually run gtk2 taffybar since I started #237 which was about half a year ago.

At least on my machine gtk3 is probably more stable than gtk2, so I think that it might be best to just release a new version with the new version of gtk.

We could also do a release without it and then another release with it, but I think it would be best to try to get as many people on to gtk3 as possible.

**Comment by IvanMalison** [comment]
Also: I know that I mentioned this before, but I'd just like to reiterate that I'd be happy to help out if you're still looking for help on the maintenance front. I think I've touched enough of the code base at this point that I have a good sense of how everything works.

**Comment by thkoch2001** [comment]
branch stable-0.5 (commit 320bec7) works perfectly for me. I love the new application menu and can't wait to have it on all of my machines!

**Comment by PierreR** [comment]
> It is just a matter of time. I'd like to at least write up a good changelog and migration guide.

@travitch How long exactly ? Another year ? What are mere users supposed to do ? Keep using `0.4.6`, go for the `0.5-stable` branch, use master, search for an alternative ?

**Comment by pltanton** [comment]
I use master version for several weeks and it looks stable, may be 1.0.0-pre or something like that, should be in Hackage?

**Comment by IvanMalison** [comment]
@PierreR I would encourage use of the master branch with a stack based installation. But I agree that we should try to get a new release on hackage.

**Comment by anarcat** [comment]
i'd love to see a taffybar release as well. i've switch to i3 recently, and while taffybar actually works with it, i'm curious to see what the new "i3wm support" entails. @travitch i encourage you to try it out with i3... i looked for other status bars and while i3status is a nice default, it does not have graphs like taffybar provides, and which I really love...

**Comment by anarcat** [comment]
oh, i've *just* noticed @IvanMalison has pushed a bunch of commits to master... are you the new maintainer? i guess this means we may hope for a new release soon?

is there a TL;DR: set of instructions on how to install the current master easily?

turns out taffybar *mostly* works with i3, except the window titles don't get update until workspace changes... minor, but still a little annoying.

**Comment by IvanMalison** [comment]
> turns out taffybar mostly works with i3, except the window titles don't get update until workspace changes... minor, but still a little annoying.

That shouldn't happen. File a bug if this still occurs on master.

> is there a TL;DR: set of instructions on how to install the current master easily?

There is https://github.com/travitch/taffybar/blob/master/quick-start.sh

> oh, i've just noticed @IvanMalison has pushed a bunch of commits to master... are you the new maintainer? i guess this means we may hope for a new release soon?

I don't have access to taffybar on hackage, so I think you're still waiting on @travitch to do that.

**Comment by travitch** [comment]
@IvanMalison What is your hackage username?  I'll try to add you as a maintainer there

**Comment by IvanMalison** [comment]
@travitch  it's eyevanmalicesun

**Comment by IvanMalison** [comment]
I'll do a release as soon I can finish fixing #230 (and I have hackage access), which will hopefully be sometime this week.

**Comment by travitch** [comment]
@IvanMalison You are now a maintainer on hackage

**Comment by IvanMalison** [comment]
Thanks @travitch

**Comment by IvanMalison** [comment]
@cdepillabout @drdo @frioux @vanjo9800 @sakshamsharma @surr @jagajaga @bgamari @abdulsattar @m-gibson You're being pinged because you have outstanding pull requests that have merge conflicts or changes requested.

I'm going to be cutting a release tomorrow, so this is the last call for any changes to make it.

**Comment by dongcarl** [comment]
Looking forward to a new release... GTK3 solves HiDPi problems with a env var. Papa bless...

**Comment by IvanMalison** [comment]
@dongcarl Oh really? How exactly does that work @dongcarl?

**Comment by dongcarl** [comment]
@IvanMalison here: https://wiki.archlinux.org/index.php/HiDPI#GDK_3_.28GTK.2B_3.29

I tried using it on some master commit 2 weeks back but it seems it messes up Xmonad's detection of how tall Taffybar is. As in: the UI scaled perfectly but it was partly obscured. Would love to test with new release.

**Comment by IvanMalison** [comment]
@dongcarl Ahh yeah that would happen if it results in a size for taffybar that exceeds what was specified. Could you file a bug about that. We'll need to account for that scaling factor when setting the strut size for the bar.

**Comment by IvanMalison** [comment]
New release is up on hackage!

**Comment by teleshoes** [comment]
congrats and thanks!
