### ISSUE TITLE
Not enough hooks?

### ISSUE THREAD

**Issue by qrilka** [travitch/taffybar#185]
On my notebook xmonad-0.13 appeared and taffybar started behaving weirdly - it was on top but any opened window was painted on top of it.
I have found solution in https://github.com/xmonad/xmonad/issues/18 which was in switching from `defaultConfig` to `desktopConfig`.
As haddocks currently talk only about `manageDocks` on top of `defaultConfig` they should probably tell about `desktopConfig` or list all of the required hooks for `taffybar` to work properly.
Also `System.Taffybar` advises integration with xmonad using dbus but `System.Taffybar.XMonadLog` blames it as deprecated

**Comment by IvanMalison** [comment]
You need to use the new `docks` config wrapper which does a few different things.

```
docks :: XConfig a -> XConfig a
docks c = c { startupHook     = docksStartupHook <+> startupHook c
            , handleEventHook = docksEventHook <+> handleEventHook c
            , manageHook      = manageDocks <+> manageHook c }
```

**Comment by IvanMalison** [comment]
We should probably update taffybars documentation about this.
