### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by frioux** [travitch/taffybar#196]
I love the idea behind taffybar (awesome-like generic bar) but I think that it doesn't have a huge corpus of examples yet, and the fact that it's a much stranger language than Lua doesn't help.

I am planning on submitting a PR to improve the README, the toplevel haskell doc, and the default taffybar.hs.  On top of that I was wondering if you could provide to me an example of how to hook into a click event on one of the existing widgets.  Given that I *think* I could reproduce some of the more advanced awesomewm toolbars and make taffybar a lot more clearly attractive.

**Comment by IvanMalison** [comment]
> On top of that I was wondering if you could provide to me an example of how to hook into a click event on one of the existing widgets.

The widgets are all of type `Gtk.Widget`. You can use a statement like

``` haskell
_ <- Gtk.on myWidget Gtk.buttonPressEvent $ liftIO doMyThing
```

Where `doMyThing` to add an action to a widget.

**Comment by frioux** [comment]
Thanks for the quick response!  Here's a simple example I'm attempting:

``` haskell
weaCallback = do
  createProcess( proc "firefox", ["https://darksky.net/34.0196,-118.487"] )

wea = weatherNew (defaultWeatherConfig "KSMO") 10

_ <- Gtk.on wea Gtk.buttonPressEvent $ liftIO weaCallback
```

I get this error:

```
Error:                                                                              
/home/frew/.config/taffybar/taffybar.hs:35:3: error:                                
    parse error on input ‘<-’                                                       
    Perhaps this statement should be within a 'do' block?    
```

---

I muddled some more and ended up with:

``` haskell
import Graphics.UI.Gtk

-- ...

tempCallback = do
  ret <- getCPUTemp ["cpu0"]
  return [fromIntegral (ret!!0)]

weaCallback = do
  createProcess( proc "firefox", ["https://darksky.net/34.0196,-118.487"] )

wea = weatherNew (defaultWeatherConfig "KSMO") 10

x = do
  _ <- Gtk.on wea Gtk.buttonPressEvent $ liftIO weaCallback
  1
```

And that errors with:
```
Error:
/home/frew/.config/taffybar/taffybar.hs:37:8: error:
    Not in scope: ‘Gtk.on’
    No module named ‘Gtk’ is imported.

/home/frew/.config/taffybar/taffybar.hs:37:19: error:
    Not in scope: ‘Gtk.buttonPressEvent’
    No module named ‘Gtk’ is imported.
```

Clearly I'm missing something simple

**Comment by IvanMalison** [comment]
You need:
``` haskell
import qualified Graphics.UI.Gtk as Gtk
```

@frioux yeah. That statement needs to be inside a do block

**Comment by frioux** [comment]
Thanks for your patience.  So here is what I have:
([in context](https://github.com/frioux/dotfiles/commit/e9a710fd417a2eb8a0989cba700693001ca57977)
``` haskell
      weaCallback = do
       unsafeSpawn "firefox https://darksky.net/34.0196,-118.487"
       return True

 -- ...

 _ <- Gtk.on wea Gtk.buttonPressEvent $ liftIO weaCallback
```

Here's the error I'm getting now:

```
Error:
/home/frew/.config/taffybar/taffybar.hs:59:19: error:
    • No instance for (Gtk.WidgetClass (IO Gtk.Widget))
        arising from a use of ‘Gtk.buttonPressEvent’
    • In the second argument of ‘Gtk.on’, namely ‘Gtk.buttonPressEvent’
      In the expression: Gtk.on wea Gtk.buttonPressEvent
      In a stmt of a 'do' block:
        _ <- Gtk.on wea Gtk.buttonPressEvent $ liftIO weaCallback
```

I really appreciate your help

**Comment by IvanMalison** [comment]
right, so you are coming up against haskell's functional nature here, and you are sort of going to have to understand what is going on with IO in order to do what you want.

Basically you need to write a new io action that takes the widget io action, gets the widget out of it, adds your button press event and then returns the widget as is

**Comment by frioux** [comment]
I got this working and will submit pull requests to improve the docs by and by; thanks
