### ISSUE TITLE
Cannot set tooltip from callback?

### ISSUE THREAD

**Issue by frioux** [travitch/taffybar#198]
I am trying to set a tooltip on my widgets. Here's one of my current widgets:

```haskell
      memReader :: IO [Double]
      memReader = do
        mi <- parseMeminfo
        w  <- mem
        let
          used :: String
          used = show (memoryUsed mi)
          total :: String
          total = show (memoryTotal mi)
          tooltip :: String
          tooltip = used ++ " / " ++ total
        _ <- Gtk.widgetSetTooltipText w (Just tooltip)
        return [memoryUsedRatio mi]

      mem :: IO Gtk.Widget
      mem = do
        btn <- pollingGraphNew memCfg 1 memReader
        ebox <- Gtk.eventBoxNew
        Gtk.containerAdd ebox btn
        _ <- Gtk.on ebox Gtk.buttonPressEvent systemEvents
        Gtk.widgetShowAll ebox
        return $ Gtk.toWidget ebox

      systemEvents :: Gtk.EventM Gtk.EButton Bool
      systemEvents = do
        e <- Gtk.eventButton
        case e of
          Gtk.LeftButton   -> unsafeSpawn "terminator -e glances"
          Gtk.RightButton  -> unsafeSpawn "terminator -e top"
          Gtk.MiddleButton -> unsafeSpawn "gnome-system-monitor"
          _ -> return ()
        return True
```

Everything here is working perfectly, except the tooltip never actually gets set.  Someone theorized in the #haskell channel that maybe the code is running in a thread, which would make sense.  Is there some other way for me to achieve what I want here?

**Comment by travitch** [comment]
Try wrapping the call to `widgetSetTooltipText` in `memReader` with a call to `postGUIAsync`.  That will send the action to the GTK event loop thread and run it there.

**Comment by frioux** [comment]
I'll try it and report back. Thanks!

--

**Comment by frioux** [comment]
Here's the callback and what I tried.  It looks like it's not getting called, is something obviously wrong?

```haskell
      memReader :: IO [Double]
      memReader = do
        mi <- parseMeminfo
        w  <- mem
        let
          used :: String
          used = show (memoryUsed mi)
          total :: String
          total = show (memoryTotal mi)
          tooltip :: String
          tooltip = used ++ " / " ++ total
        Gtk.postGUIAsync $ do
          _ <- Gtk.widgetSetTooltipText w (Just tooltip)
          return ()
        return [memoryUsedRatio mi]
```

Note that I also refactored it as follows to debug it better, and while it does print the lines, there is no tooltip being set:

```haskell
      memReader :: IO [Double]
      memReader = do
        mi <- parseMeminfo
        Gtk.postGUIAsync $ do
          w <- mem
          let
            used :: String
            used = show (memoryUsed mi)
            total :: String
            total = show (memoryTotal mi)
            tooltip :: String
            tooltip = used ++ " / " ++ total
          putStrLn tooltip
          Gtk.widgetSetTooltipText w (Just tooltip)
          return ()
        return [memoryUsedRatio mi]
```

**Comment by IvanMalison** [comment]
> and while it does print the lines

Where areyou priting lines?

**Comment by frioux** [comment]
In the second example, right before setting the tooltip.  (`putStrLn tooltip`)

**Comment by IvanMalison** [comment]
@frioux see my updated comment I think that should fix the issue for you

**Comment by frioux** [comment]
@IvanMalison Look at the very first snippet in this issue for context; it has all of the referenced variables including type.  I understand what you are saying I should do to fix it, but sadly that would basically imply, as far as I can tell, reimplementing the polling graph entirely.  My goal here was to use the existing polling graph and set the tooltip from within the data source callback.  Is that basically impossible?

And yes, I am very unfamiliar with Haskell :)

**Comment by frioux** [comment]
But I do see what you are getting at.  I can't just "update" the widget, I need to somehow replace it, I guess?  I'll ponder how to hook this in, but I still think that this maybe implies a harder refactor or replacement of the existing PollingGraph.

**Comment by IvanMalison** [comment]
> @IvanMalison Look at the very first snippet in this issue for context; it has all of the referenced variables including type. I understand what you are saying I should do to fix it, but sadly that would basically imply, as far as I can tell, reimplementing the polling graph entirely. My goal here was to use the existing polling graph and set the tooltip from within the data source callback. Is that basically impossible?

No its very possible; I described how to fix it in my post above, but perhaps I wasn't clear enough. I'll write it out for you:

**Comment by IvanMalison** [comment]
Ahh, but I'm assuming that you want the widget text to update dynamically, right?

**Comment by frioux** [comment]
yeah :)  I got it working statically before

**Comment by IvanMalison** [comment]
thankfully, its still definitely possible, just a tiny bit more complicated. I'll post a solution here in a second.

**Comment by IvanMalison** [comment]
@frioux 
``` haskell 
memCfg =
  defaultGraphConfig
  {graphDataColors = [(0.129, 0.588, 0.953, 1)], graphLabel = Just "mem"}

memCallback widget = do
  mi <- parseMeminfo
  let tooltip = printf "%s/%s" (show $ memoryUsed mi) (show $ memoryTotal mi) :: String
  Gtk.postGUIAsync $ do
    _ <- Gtk.widgetSetTooltipText widget (Just tooltip)
    return ()
  return [memoryUsedRatio mi]

mem :: IO Gtk.Widget
mem = do
  ebox <- Gtk.eventBoxNew
  btn <- pollingGraphNew memCfg 1 $ memCallback ebox
  Gtk.containerAdd ebox btn
  _ <- Gtk.on ebox Gtk.buttonPressEvent systemEvents
  Gtk.widgetShowAll ebox
  return $ Gtk.toWidget ebox
```

**Comment by IvanMalison** [comment]
I actually tested that one  so it should definitely work, I think you'll probably want to format memoryUsed and memoryTotal differently than they are currently formatted since the numbers are huge...

**Comment by IvanMalison** [comment]
probably want to just truncate the display of the last few fractionaly digits

**Comment by frioux** [comment]
yeah I was gonna tweak the formatting after it worked.  Gonna try it now.

**Comment by frioux** [comment]
Perfect!  Thanks again for your help @IvanMalison.  So what I needed to do was build a closure instead of referencing the global I guess?

**Comment by IvanMalison** [comment]
> Perfect! Thanks again for your help @IvanMalison. So what I needed to do was build a closure instead of referencing the global I guess?

Kind of, I mean you need a value of `Gtk.Widget`, not `IO Gtk.Widget`, so that you are operating on a particular widget, instead of a computation that produces a widget. Your creating two versions of the widget -- 1 that was never displayed anywhere, and 1 that lacked a tooltip.

**Comment by frioux** [comment]
ahhhh, so when I was doing `do w <- mem` before I was getting a *new* widget.  I get it now.   Thanks

**Comment by frioux** [comment]
By the way, this is what I came up with:

```haskell
      -- I can't figure out the type of this
      -- memReader :: Gtk.Widget -> IO [Double]
      memReader widget = do
        mi <- parseMeminfo
        let
          used    = round $ memoryUsed  mi :: Int
          total   = round $ memoryTotal mi :: Int
          ratio   = round $ 100 * memoryUsedRatio mi :: Int
          tooltip = printf "%i / %i (%i%%)" used total ratio :: String
        Gtk.postGUIAsync $ do
          _ <- Gtk.widgetSetTooltipText widget (Just tooltip)
          return ()
        return [memoryUsedRatio mi]
```

**Comment by IvanMalison** [comment]
The type you have there is basically correct, you just need to cast the eventbox to a widget
```
memReader :: Gtk.Widget -> IO [Double]
```

**Comment by IvanMalison** [comment]
```
btn <- pollingGraphNew memCfg 1 $ memCallback $ Gtk.toWidget ebox
```

**Comment by frioux** [comment]
Thanks again!
