### ISSUE TITLE
taffybar is covered by other applications

### ISSUE THREAD

**Issue by shwsun** [travitch/taffybar#205]
For example when I opened chromium the taffybar is now covered and is not able to be seen. My xmonad config is [here](https://github.com/shwsun/xmonad-ubuntu-conf/tree/taffybar). Is there some mis-configuration in my xmonad.hs?

**ANSWER**:
The problem is caused by xmonad-0.13, xmonad-0.12 user will be fine (which is the version come with Debian).
If you are experiencing the same problem them try edit the `taffybar.cabal` to setup the xmonad and xmonad-contrib verion.

**Comment by shwsun** [comment]
I think I may have find the problem, it seems like when I do `cabal install taffybar --gloabl" it will automatically install xmonad-0.13 which is breaking this cover thing.

**Comment by shwsun** [comment]
Hooray, I solved it myself. 
The solution is I ended up manually set the xmonad and xmonad-contrib dependencies to 0.12.

**Comment by shwsun** [comment]
This is actually a problem now. Because the Debian just updated the xmonad version to 0.13, now the taffybar is suffering from this issue unless we can solve it. I can take a stab but I know very little about haskell. Anyone has any ideas? 

Meanwhile I propose we have branches and releases for taffybar. As well as we can make new release and update more features we definitely need to test it on different environment (OS, xmonad, etc) and make it more robust. Do you guys agree?

**Comment by xrvdg** [comment]
Glancing over your xmonad.hs it looks like you have only added the manageDocks hook, and did not setup manageDocks as described in the documentation of [manageDocks](https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Hooks-ManageDocks.html). You can wrap your config with `docks` and then apply  `avoidStruts` to your layout.

**Comment by shwsun** [comment]
Done, thank you for pointing out it. We can close this for now.

I also updated the answer so someone else can benefit.

**Comment by shwsun** [comment]
Thx, I think it is solved for now.
