### ISSUE TITLE
Issues and suggestions on building

### ISSUE THREAD

**Issue by shwsun** [travitch/taffybar#207]
Hi, 

I am trying to contribute to this project (as I am using Xmonad and taffybar on Ubuntu) thus I am just throwing out suggestions and questions:
1. The `stack` and `cabal` building on Ubuntu is painful, I have played with it for some time and have no success. Later I figured out that I can already do `apt install taffybar`. Should we add this into the README?
2. I noticed that the travis CI build for stack 7.8 is always failing. Should we fix it? Or we can assume people should always do `stack upgrade` thus we can ignore the failure for that?

**Comment by travitch** [comment]
1) The apt package is out of date (which is partly my fault due to not having made a release in a long time).  A stack build will probably always be challenging due to the configuration system for taffybar.

2) It would be really nice to fix it.  It is failing for what seem to be strange cabal reasons that I haven't had time to track down.

**Comment by shwsun** [comment]
Ok, so I have poked around and figured out that it seems like some haskell upstream changes break the building -- because the last PR which passed the CI is now breaking too. We can enable a field `ignore failing` in travis.yaml to ignore the stack 7.8 case, or someone need to dive deeper into the haskell stack.

**Comment by IvanMalison** [comment]
> A stack build will probably always be challenging due to the configuration system for taffybar.

As I mentioned elsewhere, it's not actually that hard. For the time being, it's simply a matter of depending on the git head version of dyre https://github.com/IvanMalison/dotfiles/blob/4a62c2c72a1296593f64a73dd82abb6f0746911c/dotfiles/config/taffybar/stack.yaml#L9

it has been working great for me over the last week.

**Comment by IvanMalison** [comment]
#218 Could be relevant to this.

With that merged should be able to write a script that:

- installs stack
- install gtk2hsbuild tools using stack (possibly with --install-ghc)
- installs taffybar using stack (possibly with --install-ghc)
- creates the `$HOME/.config/taffybar` directory with starter stack, cabal and taffybar.hs files
- builds the users taffybar

This would make taffybar much more approachable, and reduce the number of incoming issues about building (#207 #194 #193 #158 #156 #151 #5)

**Comment by IvanMalison** [comment]
> The stack and cabal building on Ubuntu is painful, I have played with it for some time and have no success. Later I figured out that I can already do apt install taffybar. Should we add this into the README?

#218 addresses this as best as possible for now. See #193 for further discussion on what could be done to make this easier.

> I noticed that the travis CI build for stack 7.8 is always failing. Should we fix it? Or we can assume people should always do stack upgrade thus we can ignore the failure for that?

This was fixed a while ago.
