### ISSUE TITLE
Consider removing all tray code from this repository

### ISSUE THREAD

**Issue by IvanMalison** [travitch/taffybar#236]
I'm working on migrating taffybar to gtk3 ( #121, a continuation of #126  ) here:
https://github.com/IvanMalison/taffybar/tree/migrateToGTK3

and I've actually made quite a bit of progress. With a bit more work, I think it will be ready to be merged. One of the main obstacles that I'm dealing with is making the tray work. This is actually something that really should be handled completely separately, and there IS a totally separate package for the traymanager, so its not really clear to me why there is any code in taffybar at all for this widget. Perhaps it should just live in its own repository, that other users can pull in if they need it?

**Comment by travitch** [comment]
That was the most complicated bit the last time I tried to look at upgrading to gtk3.  The tray was also the primary reason I wrote taffybar initially.  The port of gtk-traymanager isn't obvious - is that the issue you are running into?  What code, in particular, did you want to remove?

**Comment by IvanMalison** [comment]
@travitch 


> The port of gtk-traymanager isn't obvious - is that the issue you are running into?

I have it compiling here: https://github.com/IvanMalison/gtk-traymanager/tree/gtk3, but I don't think its working yet.

> What code, in particular, did you want to remove?

Just the code in: src/System/Taffybar/Systray.hs It seems like that could easily just move to the other repository.
