### ISSUE TITLE
freedesktop menu widget breaks on nonexistent XDG_CONFIG_DIRS items, empty menu prefix

### ISSUE THREAD

**Issue by benley** [travitch/taffybar#240]
built at 2647bc9071fb926d460e447ba1c333c06736b7d7

I'm running taffybar on NixOS, which sets various XDG_* variables somewhat differently than typical linux distros, and the menu widget is failing to load the system menus:

```
$ result/sw/bin/taffybar 
Launching custom binary /home/benley/.cache/taffybar/taffybar-linux-x86_64

Reading /home/benley/.nix-profile/etc/xdg/menus/gnome-applications.menu
taffybar-linux-x86_64: /home/benley/.nix-profile/etc/xdg/menus/gnome-applications.menu: openFile: does not exist (No such file or directory)
```

Relevant environment:
```
$ env|grep XDG_
XDG_VTNR=7
XDG_SESSION_ID=6
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/run/opengl-driver/share:/run/opengl-driver-32/share:/etc/per-user-pkgs/benley/share:/home/benley/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
XDG_SESSION_DESKTOP=
XDG_SESSION_CLASS=user
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session3
XDG_CONFIG_DIRS=/etc/per-user-pkgs/benley/etc/xdg:/home/benley/.nix-profile/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
```

It looks like XDG_CONFIG_DIRS is the one that affects this.  Of the items listed in that variable, only `/run/current-system/sw/etc/xdg` contains a `menus` directory, but `getXdgConfigDir` just checks for the existence of the `..../etc/xdg` directory.  If there is no `menus` subdirectory, taffybar crashes.

Also, `menuWidgetNew` does not work in the case where XDG_MENU_PREFIX is empty and only `applications.menu` exists.  It currently requires that _some_ `*-applications.menu` file exists in an xdg config dir, but that's not always going to work.  On my system:

```
$ ls /run/current-system/sw/etc/xdg/menus/
applications.menu  kinfocenter.menu
```

I'm invoking the widget as `menuWidgetNew Nothing` in my taffybar.hs.

**Comment by benley** [comment]
cc @u11gh

**Comment by u11gh** [comment]
Thanks for reporting.  I shall have a look.  Though that may take some
time.

**Comment by u11gh** [comment]
Opened pullrequest #241 in order to fix these problems.  

@benley please try out.

**Comment by benley** [comment]
Awesome, thanks! I will give it a try this afternoon.

**Comment by benley** [comment]
With #241 taffybar doesn't crash anymore, but the menu widget still doesn't quite work, because applications.menu doesn't exist in the first xdg config directory it finds:

```
benley@alnitak:~$ taffybar
Configuration '/home/benley/.config/taffybar/taffybar.hs' changed. Recompiling.
Program reconfiguration successful.
Launching custom binary /home/benley/.cache/taffybar/taffybar-linux-x86_64

Error: menu file '/home/benley/.nix-profile/etc/xdg/menus/applications.menu' does not exist!
```

**Comment by benley** [comment]
I'm taking a stab at another improvement; this looks fairly easy to fix.

**Comment by IvanMalison** [comment]
@benley Can you work on top of some cleanup i did in that file so that I don't keep getting merge conflicts in #237?

**Comment by benley** [comment]
Sure - should I just grab XdgMenu.hs from #237 or does it have other interdependencies?

**Comment by IvanMalison** [comment]
I think Util.hs is the only one. I can just cherry-pick the changes out if you want.

**Comment by u11gh** [comment]
Am 15.11.2017 um 16:33 (+0000) schrieb Benjamin Staffin:
> With #241 taffybar doesn't crash anymore, but the menu widget still
> doesn't quite work, because applications.menu doesn't exist in the
> first xdg config directory it finds:

I see.  I will check the freedesktop specs but it seems quite reasonable
to just use the first *existing* menu file in the search path.  I'll fix
that.

**Comment by IvanMalison** [comment]
@benley @u11gh #242 fixed this correct? I'm going to close this, but feel free to reopen or comment if it is still an issue.

**Comment by benley** [comment]
I think so, yes.  Thanks again.

**Comment by u11gh** [comment]
I think it's OK.  (I must have lost track of this issue.  Sorry!)
