### ISSUE TITLE
Drop support for ghc 7.8?

### ISSUE THREAD

**Issue by IvanMalison** [travitch/taffybar#259]
@travitch 

The latest version of haskell-dbus doesn't support ghc 7.8 (this is causing the build error currently on master). We need this update to dbus to support #109, so I see no way forward other than to drop support for ghc 7.8 moving forward.

Thoughts?

**Comment by IvanMalison** [comment]
Feel free to revert d34d30b if you feel strongly that we should not do this.

**Comment by travitch** [comment]
Seems fine by me at this point, thanks.
