### ISSUE TITLE
Css question/guidance

### ISSUE THREAD

**Issue by PierreR** [travitch/taffybar#271]
I am trying to style the number of the active desktop (`3` in the picture). What would be the css property to do this ? As you can see I have already styled the active content as such:
 ```
.Active .Contents, .Visible .Contents {
	  background-color: @active-window-color;
}
```
![taffybar_3](https://user-images.githubusercontent.com/93115/38708508-e71f2f2c-3eb6-11e8-8fc0-9e47f16d02af.PNG)

**Comment by IvanMalison** [comment]
``` css
.Active .WorkspaceLabel {
	font-size: 12pt;
}
```

**Comment by IvanMalison** [comment]
You can use https://gitter.im/taffybar/Lobby to ask one off questions like this.
