### ISSUE TITLE
Containerize build for travis or move to other CI provider with newer distro

### ISSUE THREAD

**Issue by IvanMalison** [travitch/taffybar#272]
Travis CI currently runs on an ubuntu version that was originally released in 2014 (Truty Tahr), and as such it installs ancient versions of gtk+ and gdk when building taffybar. This is a problem for #268 because gtk-strut uses bindings that did not exist in these versions of gtk. Normally, I might try to solve this problem trying to avoid the new bindings, but in this case doing so would require calling in to functions that have been deprecated, which seems like the wrong thing to do.

This could resolve itself if something is done about travis-ci/travis-ci#5821

**Comment by travitch** [comment]
I think I might need to transfer taffybar to an organization to be able to give you admin access.  I'm not positive, but I don't see the option in the current configuration.  I don't mind doing it, but it might break some people.

**Comment by IvanMalison** [comment]
> I don't mind doing it, but it might break some people.

I think it might be helpful, but its not super urgent. I'd like to add linting support at some point.

Seems like I'll be able to get the container CI without it though.  We will need to make a public repository on docker hub for taffybar. I'm just going to go ahead and do that under my account unless you object.

**Comment by IvanMalison** [comment]
#217 now contains a Dockerfile that will be used for the containerized build. Would also be nice to add a webhook to push docker updates automatically when master is updated as this will help with caching.

**Comment by IvanMalison** [comment]
@travitch What I'd really like to do is:

https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

But I can't do that without admin access to the repository.

The reason we need to do this is that by pushing to docker hub, we can cache 90+% of the build

(install of ghc, install of dependencies etc etc.) and only spend time acttually building the code base this way. Will make CI time go down from ~30 mins to <5
