### ISSUE TITLE
Taffybar window appears on top of full screen windows

### ISSUE THREAD

**Issue by IvanMalison** [travitch/taffybar#275]
For me, this only seems to happen when the taffybar process is started AFTER the process of the window going full screen.

Also, interestingly, if float ANY window (even one not associated with the process going full screen) and make it cover taffybar, and then go full screen, the issue does not occur.

**Comment by LeifW** [comment]
For me, taffybar appears on top of windows period, if it was started after them. So with the increased height of the graphs since gtk3, or with large tray icons, I have to float windows and re-tile-them if I start / restart taffybar after they were launched, to keep taffybar from covering the tops of them.

**Comment by IvanMalison** [comment]
@LeifW Yes, that is unsurprising, but the severtiy of the issue in your case is exacerbated by #270. I suspect that what needs to be done is to tell X11 (though gtk?) to move taffybar to the very bottom (in the z dimension) of the window stack.

**Comment by IvanMalison** [comment]
@sakshamsharma @ThinkRedstone @LeifW As github seems to have noted, this has been fixed in 1c2dbad which is in the history of this branch

https://github.com/travitch/taffybar/tree/use_gtk-strut

The branch has some pretty drastic changes to taffybar that are coming soon (you will almost certainly have to rewrite your config), but it will offer a bunch of improvements.

**Comment by LeifW** [comment]
If there's an example taffybar.hs for that branch, I could give it a try (my current one doesn't compile on that branch because it says` import System.Taffybar.TaffyPager` is not found).

**Comment by IvanMalison** [comment]
You can try my config:

https://github.com/IvanMalison/dotfiles/blob/b44e57a9f4ec822e99649b1ccc5516cbcbad4fb8/dotfiles/config/taffybar/taffybar.hs#L255

though it has some git stack dependencies and stuff that you'll need to sort out.
