### ISSUE TITLE
Current version is not cabal installable

### ISSUE THREAD

**Issue by IvanMalison** [travitch/taffybar#288]
In my excitement at solving the memory leak issue, I forgot that I introduced a dependency on gtk2hs/gtk2hs#244 (which hasn't even been merged, let alone released yet), so 1.0.2 will not build with a normal cabal install :smile:

I'm open to suggestions about what to do about this.

**Comment by LeifW** [comment]
Looks like it's merged upstream, so just waiting for a release. I was going to say perhaps inlining the equivalent function into a new taffybar release in the meantime, but that module is apparently generated by some .chs? - not really sure how that works.
