### ISSUE TITLE
Missing xml

### ISSUE THREAD

**Issue by GregorySchwartz** [travitch/taffybar#363]
Cannot compile from Hackage:

`dbus-xml/org.freedesktop.UPower.Device.xml: openFile: does not exist (No such file or directory)`

I think all of the files in `dbus-xml` need to be added to the cabal file.

**Comment by IvanMalison** [comment]
@GregorySchwartz in the mean time, you should be able to install from source pretty easily

**Comment by IvanMalison** [comment]
I'll do a release soon

**Comment by puffnfresh** [comment]
Thanks @IvanMalison. A release would be very useful :heart:
