### ISSUE TITLE
taffybar-0.1.3 doesn't really need gtk >= 0.12.1

### ISSUE THREAD

**Issue by juhp** [travitch/taffybar#4]
Hi, I see you bumped the gtk dependency for ghc-7.2 (and same for gtk-traymanager),
and I am just wondering if this really helps anyone? :)

Yes, I understand that ghc-7.2 needs gtk-0.12.1 but
the latest taffybar code builds fine with gtk-0.12 on ghc-7.0, and
there is not really any advantage for ghc-7.0 users to upgrade
to gtk-0.12.1.  So from my point of view (tell me if I am wrong:)
bumping the gtk depends is just making life harder for 7.0 users,
which is still the default for haskell-platform.  So my suggestion
is to relax the dependency on gtk to 0.12.\* again.

Thanks for taffybar. :)

**Comment by IvanMalison** [comment]
closing since we're now on gtk3
