### ISSUE TITLE
Crash when remmina is running

### ISSUE THREAD

**Issue by bgamari** [travitch/taffybar#429]
**Describe the bug**

It seems that taffybar is not robust against invalid icon data.

**To Reproduce**

1. Start `taffybar`
2. Start `remmina`

Observe that `taffybar` crashes with,
```
taffybar-ben: Image file “/nix/store/fflh86pf9mjcjmf4ksz8lsiqb8394n1q-remmina-1.2.31.3/share/icons/hicolor” contains no data (0)
```

**Expected behavior**
Taffybar should continue to run.

**Screenshots**

**Version information**
Taffybar version (or git sha if building from source): f34b2ec1884574ad6ff9fe8986afef942333e9f1
Installation method (nix/stack/cabal/arch packages): Nix
Gtk version: 3.22.30

**Comment by IvanMalison** [comment]
@bgamari Can you clarify whether this is the SNI Icon or the workspace icon?

**Comment by IvanMalison** [comment]
I just ran remmina, installed from nixpkgs on nixos though version (1.2.32.1 (git n/a)), and I did not experience a crash 
![remmina](https://user-images.githubusercontent.com/1246619/49691463-67caa500-faf7-11e8-8117-865d6d6297a1.png)

Any ideas about why we are seeing different behavior?

**Comment by bgamari** [comment]
I honestly have no idea why you wouldn't see the issue. However, the fact that the `Image file ... contains no data` error is treated as fatal is certainly a bug. Unfortunately I haven't yet been able to work out where it comes from.

**Comment by IvanMalison** [comment]
> However, the fact that the `Image file ... contains no data` error is treated as fatal is certainly a bug.

Yeah, agreed, I just need a repro to figure out which component it is coming from.

I guess I can try to manually reproduce the issue by trying to manually point towards invalid image data to see what happens in that scenario.

**Comment by bgamari** [comment]
I'm not certain but I suspect it is an SNI icon.

**Comment by IvanMalison** [comment]
My guess is that this was #403
