### ISSUE TITLE
XBM/XPM Icon support

### ISSUE THREAD

**Issue by NickHu** [travitch/taffybar#47]
Would it be possible to implement icon support with Graphics.X11.Xlib?
This landed in Xmobar quite some time ago, and their process seems to be relatively well documented here: https://github.com/jaor/xmobar/pull/87

**Comment by IvanMalison** [comment]
@NickHu This approach doesn't make as much sense for taffybar because taffybar is gtk based. You can look at IconImages and https://github.com/travitch/taffybar/blob/7af3d7251e340ed058cab7e8b263020ab000ab32/src/System/Taffybar/WorkspaceHUD.hs#L839 to figure out how to add images.
