### ISSUE TITLE
mtl 2.3

### ISSUE THREAD

**Issue by jchia** [travitch/taffybar#573]
taffybar does not build with mtl 2.3. taffybar directly depends on ConfigFile (in taffybar.cabal, though there is no actual usage in the .hs code) and indirectly depends on ConfigFile through xdg-desktop-entry.

ConfigFile requires mtl < 2.3 and is so old that it is growing cobwebs and it has no GitHub page for people to contribute updates for mtl-2.3 compatibility.

xdg-desktop-entry also has no GitHub page, so people canot contribute updates.

For what xdg-desktop-entry does, the ini package seems like a better option than ConfigFile. There is a github page and the last Hackage upload was much more recent.

On Hackage, I see that xdg-desktop-entry has the same uploader as taffy bar, namely eyevanmalicesun, so I assume the author is the same.

Can a GitHub page be made for xdg-desktop-entry? I think some people would be happy to contribute an update to move from ConfigFile to ini as the necessary change seems trivial.

**Comment by colonelpanic8** [comment]
@jchia very open to prs.

**Comment by jchia** [comment]
After the [PR for xdg-desktop-entry](https://github.com/taffybar/xdg-desktop-entry/pull/2) and #574, I believe one issue remains that blocks building `taffybar` with GHC 9.6: https://github.com/cohomology/gi-cairo-render/pull/12

Whereas there has been no response to that PR for months, I see that eyevanmalicesun is listed on Hackage as a maintainer of `gi-cairo-connector`. @colonelpanic8: Are you eyevanmalicesun? Do you get to merge PRs in that `gi-cairo-render` repo?

**Comment by colonelpanic8** [comment]
Yes, but that was kind of a temporary arrangement from the last time the maintainer did not reapond. I don't think I have access to the GitHub repo either... Just hackage.

**Comment by colonelpanic8** [comment]
@jchia ah okay. I'll look in to it this weekend.

**Comment by Vekhir** [comment]
@colonelpanic8 Did you look at bumping `mtl` on Hackage for `gi-cairo-connector`?
I can confirm that with the packages on Hackage, `gi-cairo-connector` works fine when bumping `mtl`. After that, everything else builds fine too.

@jchia Once above action has been taken, would you consider making a new release for the convenience of Arch packaging? This primarily concerns `xdg-desktop-entry`.

**Comment by jchia** [comment]
I'm not a maintainer of any of these. @colonelpanic8 is.

**Comment by Vekhir** [comment]
> I'm not a maintainer of any of these Hackage packages. @colonelpanic8 is.

@jchia Now that you say it I don't know why I thought you were. Sorry.

**Comment by colonelpanic8** [comment]
@Vekhir @jchia 

thanks for investigating.

Sorry that I kind of lost sight of this.

Cool going to see if I can bump gi-cairo-connector today.

**Comment by colonelpanic8** [comment]
@jchia wait I think that inaki already basically did what you're asking for:

https://hackage.haskell.org/package/gi-cairo-render-0.1.2/src/gi-cairo-render.cabal

0.1.2 has no upper bound on mtl at all
