### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by mathstuf** [travitch/taffybar#61]
I'm the developer/maintainer of X.H.DynamicBars in xmonad-contrib. It'd be nice if taffybar integrated with it. I see a few ways it could be done
- DBus method call for monitor add/remove events (if keeping a single taffybar instance which draws multiple bars)
- Take a monitor number on the command line (multiple instances; one per screen)

Maybe there's a better way?

**Comment by mathstuf** [comment]
I don't see a commit that does that. Is it pushed?

**Comment by IvanMalison** [comment]
@mathstuf it probably isn't in taffybar -- you can just do it in the main of your config
``` haskell
main = do
  monString <- getEnv "TAFFYBAR_MONITOR"
  let monitorNumber = fromMaybe 1 $ readMaybe monString
  ... rest of your config, making sure to set
defaultTaffybar
    defaultTaffybarConfig
    { startWidgets = ...
    , endWidgets = 
    , monitorNumber = monitorNumber
      }
```

that will need imports
``` haskell
import Data.Maybe
import Text.Read
import System.Environment
```

**Comment by alem0lars** [comment]
What if I detach the screen and reattach?

**Comment by IvanMalison** [comment]
Just trigger a restart for each monitor that is active (you can use xrandr or whatever).

Alternatively, #183 will be amended shortly to handle this!

**Comment by IvanMalison** [comment]
This can be closed now.
