### ISSUE TITLE
Should work even when started before dbus

### ISSUE THREAD

**Issue by nomeata** [travitch/taffybar#83]
Hi,

when starting taffybar from a script sourced by xinit, it may be the case that it is started before dbus is available, and I get

```
Jul 19 17:14:42 kirk /etc/gdm3/Xsession[19419]: taffybar-linux-x86_64: ClientError {clientErrorMessage = "connectSession: DBUS_SESSION_BUS_ADDRESS is missing or invalid.", clientErrorFatal = True}
```

in the logs. It should handle this gracefully and just begin to use dbus when it is available.

**Comment by IvanMalison** [comment]
Taffybars dbus dependency is going to grow stronger. I think we will likely start to use it to handle logging requests, and it is already used to toggle monitors on and off. I don't think this will be a goal moving forward.
