### ISSUE TITLE
Too many wakeups in clock and cpu widget

### ISSUE THREAD

**Issue by nomeata** [travitch/taffybar#84]
powertop lists taffybar as the worst offender. Commenting out the widgets one by one I found that of those that I use, most behave well (e.g. block until something happens). But the cpu and clock widgets cause many updates per seconds (~70/s  resp. ~44/s), despite being told to update once per second.

I didn’t debug this yet.

For the clock widget: Wouldn’t it make more sense to sleep until the time changes the next time? A bit annoying to implement that logic, but it would prevent a few unnecessary wakeups.

**Comment by dyfrgi** [comment]
Moving to 0.4.4 from an earlier version reduced wakeups quite a lot, so thanks for this change.

Has anyone done work on a coordinated wakeup scheme? If not, I might take a crack at it.

**Comment by travitch** [comment]
Glad to hear it helped.  As far as I know, nobody has looked at a coordinated wakeup scheme yet.  I'm interested, though I am not sure how much it will really help.  Weather widgets poll on the order of minutes and the clock only polls on 30 second to minute intervals.  CPU and memory monitors are probably the worst offenders and do wake up a few times a second - they might benefit.  I'd be thrilled if coordinated wakeups introduced significant savings, and still happy if they help at all.

**Comment by dyfrgi** [comment]
Right - weather and clock I wouldn't expect to benefit much, if at all. It's the system monitors where I'd expect to see benefit, especially for users with many of them.

**Comment by travitch** [comment]
That is true - I only use two, but it would be reasonable to have more.  With that in mind I am very interested again

**Comment by IvanMalison** [comment]
Seems like the original issue was fixed here:

I've filed #286 for the coordinated wakeup system in case that ever becomes an issue
