### ISSUE TITLE
multimonitor support in pager

### ISSUE THREAD

**Issue by zabbal** [travitch/taffybar#93]
TaffyPager should correctly detect addition/removal of monitors and visually highlight which workspaces currently visible through monitors and which one is active at the moment.

**Comment by saksham0808** [comment]
I use a udev rule to detect addition/removal of monitors.Its perhaps more efficient than querying monitors periodically.
```
KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="$HOME/.Xauthority", RUN+="$HOME/.myscripts/hotplug_monitor.sh"
```
Discussion?

**Comment by travitch** [comment]
So taffybar currently handles detecting monitor changes through GDK (https://developer.gnome.org/gdk3/stable/GdkScreen.html#GdkScreen-monitors-changed).  I'm not sure how it does things internally, but it seems to work fine with changes via xrandr.

Are there other usecases or shortcomings you know of in the current setup?  I'm certainly interested in making sure that works well.

**Comment by saksham0808** [comment]
I'm actually surprised to see that it is supposed to work with multimonitor addition/removal. It never worked for me. So when I removed my monitor from my laptop, thanks to XMonad, taffybar would get lost (getting displayed on a monitor which doesn't exist), and I'd have to manually disable the HDMI output monitor (or use my script). This might be a bug, as the above comment seems to indicate that its supposed to detect these kind of events.
It was for this very reason that I wrote the udev rule which would call my script when the HDMI port emits the monitor changed event.

**Comment by travitch** [comment]
Ah, in that regard I suppose you could consider it broken.  I think
that is because XRandR supports an unintuitive state where a monitor
is allowed to be "enabled but detached".  Taffybar (or, more
accurately, GDK) consider the set of enabled monitors in XRandR as
ground truth.

If you want an instant response when you unplug a monitor, the easiest
thing to do is to just poke XRandR and tell it to reconfigure
(possibly via udev).  Taffybar would respond to that.

I’m inclined to leave the complex logic to XRandR, since that seems
like the right place for it…

**Comment by saksham0808** [comment]
That's very much how my setup is currently. This is then not in the purview of taffybar I guess, but more of a design thing with XRandR. Though it would be nice if Taffybar can adjust the display monitor atleast on changes. Again, that's up to GDK. Reworking might not be plain.

**Comment by IvanMalison** [comment]
> TaffyPager should correctly detect addition/removal of monitors and visually highlight which workspaces currently visible through monitors and which one is active at the moment.

Taffybar handles this with System.Taffybar.Hooks.PagerHints in conjunction with either WorkspaceHUD or WorkspaceSwitcher.

It seems like discussion in this issue veered off into tangentially related things, but the original issue is handled, so I'm going to close. Dicussion about handling montiros being added/removed at runtime will continue at #262.
